apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mariadb-pass
  literals:
  - password=redhat
- name: mariadbuser-pass
  literals:
  - password1234=redhat
resources:
  - mariabd.yml
  - cloud.yml